### ISSUE TITLE
フッターに関するページの作成（ゆり）

### ISSUE THREAD

**Issue by daichi3102** [easyteam51/easyquestions#11]
## お問い合わせ、プライバシーポリシー、利用規約ページの作成

- [x] お問い合わせ用のgoogleフォームの作成
別タブ（新規タブ）で開くようにする
- [x] プライバシーページの作成
- [x] 利用規約ページの作成
- [x] ログインしてない場合にトップページ以外に画面遷移ができない状態にする
- [ ] scafoldで作った質問機能に関するファイルを全て削除し、scafoldを使わずに消す前と同じ機能を実装

**Comment by yamazaki-yuri** [comment]
・フッターにある利用規約のリンクをクリックすると利用規約が表示されるよう実装しました
・フッターにあるprivacy_policyをクリックするとプラーバシーポリシーが表示されるよう実装しました
・Google Formでお問い合わせフォームを作成しました
　・フッターのリンクからとプライバシーポリシーからお問い合わせできるようリンクを作成しました
・フッターの位置が変動してしまう問題を解消しました
・ログインする前のユーザーがトップページにアクセスできてしまう問題を解消しました
[https://qiita.com/jinta_02/items/78816007414ca1f8f06d](url)
