### ISSUE TITLE
エラーメッセージファイルの作成（ゆり）

### ISSUE THREAD

**Issue by daichi3102** [easyteam51/easyquestions#15]
## パーシャルでのエラーメッセージの作成

- [x] views配下のshared配下にパーシャルファイルの作成
- [x] 質問投稿時や回答時にエラーメッセージファイルが使用されるか確認

**Comment by yamazaki-yuri** [comment]
views/shared配下に_error_message.html.erbを作成しました。
config/locales/ja.ymlのactiverecordにquestionとanswerを追加しました。
質問の新規作成と編集・回答のフォームにバリデーションエラーメッセージが表示されるように実装しました。
